In [1]:
import pandas as pd
from pprint import pprint

In [2]:
df = pd.read_csv('Resources/Data/clean_data.csv')
df.head()

,Unnamed: 0,IMDB ID,Title,Director,Actor,Year,Box Office,Rating,IMDB Rating,IMDB Votes,Metascore
0,0,tt1375666,Inception,Christopher Nolan,Leonardo DiCaprio,2010,292568851.0,PG-13,8.8,1953512.0,74.0
1,1,tt1345836,The Dark Knight Rises,Christopher Nolan,Christian Bale,2012,448130642.0,PG-13,8.4,1454342.0,78.0
2,2,tt0816692,Interstellar,Christopher Nolan,Ellen Burstyn,2014,158737441.0,PG-13,8.6,1413039.0,74.0
3,3,tt1853728,Django Unchained,Quentin Tarantino,Jamie Foxx,2012,162804648.0,R,8.4,1282957.0,81.0
4,4,tt0848228,The Avengers,Joss Whedon,Robert Downey Jr.,2012,623279547.0,PG-13,8.0,1225316.0,69.0

In [3]:
selected_features = df.drop(columns=["Unnamed: 0",
                            "IMDB ID", 
                            "Title",
                            "Year",
                            "Metascore"],
                            axis=1)

In [4]:
dummyX = pd.get_dummies(selected_features)
dummyX

,Box Office,IMDB Rating,IMDB Votes,Director_Abbas Kiarostami,Director_Abdellatif Kechiche,Director_Abderrahmane Sissako,Director_Abe Sylvia,Director_Abel Ferrara,Director_Adam Green,Director_Adam Kassen,...,Actor_ZoÃ« Bell,Rating_G,Rating_NC-17,Rating_Not Rated,Rating_PG,Rating_PG-13,Rating_R,Rating_TV-MA,Rating_TV-Y7,Rating_Unrated
0,292568851.0,8.8,1953512.0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,448130642.0,8.4,1454342.0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,158737441.0,8.6,1413039.0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,162804648.0,8.4,1282957.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,623279547.0,8.0,1225316.0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1327,1065439.0,5.8,4453.0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1328,5669081.0,6.6,4415.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1329,904216.0,6.2,4305.0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1330,69236.0,6.6,4279.0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1331,5086.0,6.7,4223.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [5]:
X = dummyX
y = df["Box Office"]

print("Shape: ", X.shape, y.shape)

Shape:  (1332, 1705) (1332,)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [7]:
X_train.head()

,Box Office,IMDB Rating,IMDB Votes,Director_Abbas Kiarostami,Director_Abdellatif Kechiche,Director_Abderrahmane Sissako,Director_Abe Sylvia,Director_Abel Ferrara,Director_Adam Green,Director_Adam Kassen,...,Actor_ZoÃ« Bell,Rating_G,Rating_NC-17,Rating_Not Rated,Rating_PG,Rating_PG-13,Rating_R,Rating_TV-MA,Rating_TV-Y7,Rating_Unrated
1005,408719.0,6.2,20208.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
644,21984384.0,6.7,63212.0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1182,2022.0,6.1,9140.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1124,2400000.0,7.0,12645.0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
178,99733121.0,6.7,255646.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [8]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler().fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(X_train_scaled, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [10]:
from sklearn.metrics import mean_squared_error, r2_score

predicted = model.predict(X_test)

mse = mean_squared_error(y_test, predicted)
r2 = r2_score(y_test, predicted)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2 ): {r2}")

Mean Squared Error (MSE): 8269444975456968.0
R-squared (R2 ): -0.14794964711248126

In [11]:
model.score(X_test, y_test)

0.009009009009009009